# Generated by Django 4.1 on 2022-08-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="violation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
